### PR TITLE
Bug/NQ-992: Correct endianness of generated packed structs

### PR DESCRIPTION
**Pull request by Jonah-Foley**
https://nu-quantum.youtrack.cloud/issue/NQ-992/Correct-endianness-of-generated-packed-structs

### CODE REVIEW

**Comment by Jonah-Foley** [comment]
image

output of register `r4` in `test_wide_regs` test.

**Comment by Jonah-Foley** [comment]
I dont believe we need to update anything else (such as the auto generated comments) as despite the change in endianness the absolute start address of each register remains the same. I have trialled this change on my Phaser test suite and it seems to work.

**Review by ghost — COMMENTED** [review]
Looks good.  Only comment is that you have the same changes to `node.py` in two PRs.  This will be hard for Git to merge correctly when you rebase on HEAD so best to take it out of this PR.

**Review by ghost — APPROVED** [review]
Nice.

**Pull request merged**
